### ISSUE TITLE
Issue on macbook

### ISSUE THREAD

**Issue by ThomasArtigue** [jlolling/talendcomp_tGoogleAnalytics4Input#1]
Hello,

The component work on windows, but on mac os doesn't work. 
We have a error : 
`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at de.jlo.talendcomp.google.analytics.ga4.GoogleAnalyticsBase.<init>(GoogleAnalyticsBase.java:35)
	at de.jlo.talendcomp.google.analytics.ga4.v1.GoogleAnalyticsInput.<init>(GoogleAnalyticsInput.java:44)
	at datawarehouse.ga_example_0_1.GA_example.tGoogleAnalytics4Input_1Process(GA_example.java:553)
	at datawarehouse.ga_example_0_1.GA_example.runJobInTOS(GA_example.java:1334)
	at datawarehouse.ga_example_0_1.GA_example.main(GA_example.java:1070)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)`

My version on talend is : 
- Version: 8.0.1
- Build id: R2023-06

Version java 
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)

I download this version : v_1.0__tGoogleAnalytics4Input-1.0

Do you have any idea ?

I try to push a new jar log4j, I try to download config default on talend.

Merci

**Comment by jlolling** [comment]
Hi Thomas,

I can only guess there is a huge difference in the Java version between both systems. I am developing all of my stuff on a Mac.
I have Java 11 running.

Best regards
Jan

**Comment by ThomasArtigue** [comment]
Hi,
Thanks for the reply.
I tried to install java 11 with the same result.
It's java good or not ?

openjdk version "11.0.19" 2023-04-18

OpenJDK Runtime Environment Homebrew (build 11.0.19+0)

OpenJDK 64-Bit Server VM Homebrew (build 11.0.19+0, mixed mode)

Thomas Artigue

*Data Manager Group*


[image: Logo DNV.png]

www.recommerce.com

www.recommerce-group.com

https://fr.linkedin.com/company/recommercegroup

Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
- 94250 GENTILLY - FRANCE

*The content of this email is confidential and only intended for the
recipient mentioned in the message*. It is strictly forbidden to share this
message in whole or in part with any third party without a written consent
of the sender. If you received this message by mistake, please reply to
this message and follow with its deletion, so that we can ensure such a
mistake does not occur in the future.
*Please note that the Recommerce® brand and logo are registered at the
EUIPO and in Switzerland and belong to Recommerce Solutions in these areas.
Any reproduction, in whole or in part of these trademarks or logos made
without express authorization is prohibited under the European Union's
trademark regulation 2017/1001 and the Swiss Federal law. *

Recommerce® Management System is ISO 14001 (environment), ISO 9001
(quality) and ISO 27001 (Information Security) certified by DNV. The
company's products are certified under the Label "RECQ" verified by DEKRA
Certifications.




Le jeu. 6 juil. 2023 à 22:57, Jan Lolling ***@***.***> a
écrit :

> Hi Thomas,
>
> I can only guess there is a huge difference in the Java version between
> both systems. I am developing all of my stuff on a Mac.
> I have Java 11 running.
>
> Best regards
> Jan
>

**Comment by jlolling** [comment]
Did you checked if your installed Java will be used?

java -version

Best regards
Jan

ThomasArtigue ***@***.***> schrieb am Fr., 7. Juli 2023,
11:52:

> Hi,
> Thanks for the reply.
> I tried to install java 11 with the same result.
> It's java good or not ?
>
> openjdk version "11.0.19" 2023-04-18
>
> OpenJDK Runtime Environment Homebrew (build 11.0.19+0)
>
> OpenJDK 64-Bit Server VM Homebrew (build 11.0.19+0, mixed mode)
>
> Thomas Artigue
>
> *Data Manager Group*
>
>
> [image: Logo DNV.png]
>
> www.recommerce.com
>
> www.recommerce-group.com
>
> https://fr.linkedin.com/company/recommercegroup
>
> Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
> - 94250 GENTILLY - FRANCE
>
> *The content of this email is confidential and only intended for the
> recipient mentioned in the message*. It is strictly forbidden to share
> this
> message in whole or in part with any third party without a written consent
> of the sender. If you received this message by mistake, please reply to
> this message and follow with its deletion, so that we can ensure such a
> mistake does not occur in the future.
> *Please note that the Recommerce® brand and logo are registered at the
> EUIPO and in Switzerland and belong to Recommerce Solutions in these
> areas.
> Any reproduction, in whole or in part of these trademarks or logos made
> without express authorization is prohibited under the European Union's
> trademark regulation 2017/1001 and the Swiss Federal law. *
>
> Recommerce® Management System is ISO 14001 (environment), ISO 9001
> (quality) and ISO 27001 (Information Security) certified by DNV. The
> company's products are certified under the Label "RECQ" verified by DEKRA
> Certifications.
>
>
>
>
> Le jeu. 6 juil. 2023 à 22:57, Jan Lolling ***@***.***> a
> écrit :
>
> > Hi Thomas,
> >
> > I can only guess there is a huge difference in the Java version between
> > both systems. I am developing all of my stuff on a Mac.
> > I have Java 11 running.
> >
> > Best regards
> > Jan
> >

**Comment by ThomasArtigue** [comment]
yes
 java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Homebrew (build 11.0.19+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.19+0, mixed mode)


Thomas Artigue

*Data Manager Group*


[image: Logo DNV.png]

www.recommerce.com

www.recommerce-group.com

https://fr.linkedin.com/company/recommercegroup

Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
- 94250 GENTILLY - FRANCE

*The content of this email is confidential and only intended for the
recipient mentioned in the message*. It is strictly forbidden to share this
message in whole or in part with any third party without a written consent
of the sender. If you received this message by mistake, please reply to
this message and follow with its deletion, so that we can ensure such a
mistake does not occur in the future.
*Please note that the Recommerce® brand and logo are registered at the
EUIPO and in Switzerland and belong to Recommerce Solutions in these areas.
Any reproduction, in whole or in part of these trademarks or logos made
without express authorization is prohibited under the European Union's
trademark regulation 2017/1001 and the Swiss Federal law. *

Recommerce® Management System is ISO 14001 (environment), ISO 9001
(quality) and ISO 27001 (Information Security) certified by DNV. The
company's products are certified under the Label "RECQ" verified by DEKRA
Certifications.




Le ven. 7 juil. 2023 à 21:01, Jan Lolling ***@***.***> a
écrit :

> Did you checked if your installed Java will be used?
>
> java -version
>
> Best regards
> Jan
>
> ThomasArtigue ***@***.***> schrieb am Fr., 7. Juli 2023,
> 11:52:
>
> > Hi,
> > Thanks for the reply.
> > I tried to install java 11 with the same result.
> > It's java good or not ?
> >
> > openjdk version "11.0.19" 2023-04-18
> >
> > OpenJDK Runtime Environment Homebrew (build 11.0.19+0)
> >
> > OpenJDK 64-Bit Server VM Homebrew (build 11.0.19+0, mixed mode)
> >
> > Thomas Artigue
> >
> > *Data Manager Group*
> >
> >
> > [image: Logo DNV.png]
> >
> > www.recommerce.com
> >
> > www.recommerce-group.com
> >
> > https://fr.linkedin.com/company/recommercegroup
> >
> > Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue
> Lénine
> > - 94250 GENTILLY - FRANCE
> >
> > *The content of this email is confidential and only intended for the
> > recipient mentioned in the message*. It is strictly forbidden to share
> > this
> > message in whole or in part with any third party without a written
> consent
> > of the sender. If you received this message by mistake, please reply to
> > this message and follow with its deletion, so that we can ensure such a
> > mistake does not occur in the future.
> > *Please note that the Recommerce® brand and logo are registered at the
> > EUIPO and in Switzerland and belong to Recommerce Solutions in these
> > areas.
> > Any reproduction, in whole or in part of these trademarks or logos made
> > without express authorization is prohibited under the European Union's
> > trademark regulation 2017/1001 and the Swiss Federal law. *
> >
> > Recommerce® Management System is ISO 14001 (environment), ISO 9001
> > (quality) and ISO 27001 (Information Security) certified by DNV. The
> > company's products are certified under the Label "RECQ" verified by
> DEKRA
> > Certifications.
> >
> >
> >
> >
> > Le jeu. 6 juil. 2023 à 22:57, Jan Lolling ***@***.***> a
> > écrit :
> >
> > > Hi Thomas,
> > >
> > > I can only guess there is a huge difference in the Java version
> between
> > > both systems. I am developing all of my stuff on a Mac.
> > > I have Java 11 running.
> > >
> > > Best regards
> > > Jan
> > >

**Comment by ThomasArtigue** [comment]
Do you have a link to your java install ?


Thomas Artigue

*Data Manager Group*


[image: Logo DNV.png]

www.recommerce.com

www.recommerce-group.com

https://fr.linkedin.com/company/recommercegroup

Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
- 94250 GENTILLY - FRANCE

*The content of this email is confidential and only intended for the
recipient mentioned in the message*. It is strictly forbidden to share this
message in whole or in part with any third party without a written consent
of the sender. If you received this message by mistake, please reply to
this message and follow with its deletion, so that we can ensure such a
mistake does not occur in the future.
*Please note that the Recommerce® brand and logo are registered at the
EUIPO and in Switzerland and belong to Recommerce Solutions in these areas.
Any reproduction, in whole or in part of these trademarks or logos made
without express authorization is prohibited under the European Union's
trademark regulation 2017/1001 and the Swiss Federal law. *

Recommerce® Management System is ISO 14001 (environment), ISO 9001
(quality) and ISO 27001 (Information Security) certified by DNV. The
company's products are certified under the Label "RECQ" verified by DEKRA
Certifications.

**Comment by ThomasArtigue** [comment]
I try to configure in studio
 [image: image.png]

Thomas Artigue

*Data Manager Group*


[image: Logo DNV.png]

www.recommerce.com

www.recommerce-group.com

https://fr.linkedin.com/company/recommercegroup

Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
- 94250 GENTILLY - FRANCE

*The content of this email is confidential and only intended for the
recipient mentioned in the message*. It is strictly forbidden to share this
message in whole or in part with any third party without a written consent
of the sender. If you received this message by mistake, please reply to
this message and follow with its deletion, so that we can ensure such a
mistake does not occur in the future.
*Please note that the Recommerce® brand and logo are registered at the
EUIPO and in Switzerland and belong to Recommerce Solutions in these areas.
Any reproduction, in whole or in part of these trademarks or logos made
without express authorization is prohibited under the European Union's
trademark regulation 2017/1001 and the Swiss Federal law. *

Recommerce® Management System is ISO 14001 (environment), ISO 9001
(quality) and ISO 27001 (Information Security) certified by DNV. The
company's products are certified under the Label "RECQ" verified by DEKRA
Certifications.

**Comment by jlolling** [comment]
You mean on a Mac?
Could you please print out the Java version used in the job?

In a tJava
System.out.println(System.getProperty(“java.version”));

Best regards
Jan

**Comment by jlolling** [comment]
https://docs.oracle.com/en/java/javase/11/install/installation-jdk-macos.html#GUID-2FE451B0-9572-4E38-A1A5-568B77B146DE

**Comment by ThomasArtigue** [comment]
I check your link

the java version on studio
[image: image.png]

Thomas Artigue

*Data Manager Group*


[image: Logo DNV.png]

www.recommerce.com

www.recommerce-group.com

https://fr.linkedin.com/company/recommercegroup

Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
- 94250 GENTILLY - FRANCE

*The content of this email is confidential and only intended for the
recipient mentioned in the message*. It is strictly forbidden to share this
message in whole or in part with any third party without a written consent
of the sender. If you received this message by mistake, please reply to
this message and follow with its deletion, so that we can ensure such a
mistake does not occur in the future.
*Please note that the Recommerce® brand and logo are registered at the
EUIPO and in Switzerland and belong to Recommerce Solutions in these areas.
Any reproduction, in whole or in part of these trademarks or logos made
without express authorization is prohibited under the European Union's
trademark regulation 2017/1001 and the Swiss Federal law. *

Recommerce® Management System is ISO 14001 (environment), ISO 9001
(quality) and ISO 27001 (Information Security) certified by DNV. The
company's products are certified under the Label "RECQ" verified by DEKRA
Certifications.




Le mar. 11 juil. 2023 à 15:16, Jan Lolling ***@***.***> a
écrit :

>
> https://docs.oracle.com/en/java/javase/11/install/installation-jdk-macos.html#GUID-2FE451B0-9572-4E38-A1A5-568B77B146DE
>

**Comment by ThomasArtigue** [comment]
And you, what is your version of java, can you show your java -version?
(maybe I try to install and configure the same java)
On my side 3 Mac with same issue

Thomas Artigue

*Data Manager Group*


[image: Logo DNV.png]

www.recommerce.com

www.recommerce-group.com

https://fr.linkedin.com/company/recommercegroup

Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
- 94250 GENTILLY - FRANCE

*The content of this email is confidential and only intended for the
recipient mentioned in the message*. It is strictly forbidden to share this
message in whole or in part with any third party without a written consent
of the sender. If you received this message by mistake, please reply to
this message and follow with its deletion, so that we can ensure such a
mistake does not occur in the future.
*Please note that the Recommerce® brand and logo are registered at the
EUIPO and in Switzerland and belong to Recommerce Solutions in these areas.
Any reproduction, in whole or in part of these trademarks or logos made
without express authorization is prohibited under the European Union's
trademark regulation 2017/1001 and the Swiss Federal law. *

Recommerce® Management System is ISO 14001 (environment), ISO 9001
(quality) and ISO 27001 (Information Security) certified by DNV. The
company's products are certified under the Label "RECQ" verified by DEKRA
Certifications.

**Comment by ThomasArtigue** [comment]
That is good link for download component ?

https://github.com/TalendExchange/Components/tree/main/archive/Jan%20Lolling/components/tGoogleAnalytics4Input/files

Thomas Artigue

*Data Manager Group*


[image: Logo DNV.png]

www.recommerce.com

www.recommerce-group.com

https://fr.linkedin.com/company/recommercegroup

Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
- 94250 GENTILLY - FRANCE

*The content of this email is confidential and only intended for the
recipient mentioned in the message*. It is strictly forbidden to share this
message in whole or in part with any third party without a written consent
of the sender. If you received this message by mistake, please reply to
this message and follow with its deletion, so that we can ensure such a
mistake does not occur in the future.
*Please note that the Recommerce® brand and logo are registered at the
EUIPO and in Switzerland and belong to Recommerce Solutions in these areas.
Any reproduction, in whole or in part of these trademarks or logos made
without express authorization is prohibited under the European Union's
trademark regulation 2017/1001 and the Swiss Federal law. *

Recommerce® Management System is ISO 14001 (environment), ISO 9001
(quality) and ISO 27001 (Information Security) certified by DNV. The
company's products are certified under the Label "RECQ" verified by DEKRA
Certifications.

**Comment by jlolling** [comment]
Java configuration
<img width="1082" alt="Screenshot 2023-07-11 at 15 28 37" src="https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/assets/8038781/b3fb70b1-9db5-409e-a6e8-eb3406184f0e">

and Log4J configuration:
<img width="1001" alt="Screenshot 2023-07-11 at 15 30 09" src="https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/assets/8038781/e66c669f-c4e2-4b4d-80ee-7b2cf8280975">

**Comment by jlolling** [comment]
NO, please do not use this mostly out-dated archive!

https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/releases <https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/releases>

Best regards
Jan

**Comment by ThomasArtigue** [comment]
All good !!!!
Thank's it's works, i think my version log4j it's a problem (used log4j 1)
So i download good component with your link
I configure a same java (but with other java it's ok)
I modify the conf of log4j to log4j2
And after re-build pom.xml (very long time:) )
It works !
Many thanks
[image: image.png]

Thomas Artigue

*Data Manager Group*


[image: Logo DNV.png]

www.recommerce.com

www.recommerce-group.com

https://fr.linkedin.com/company/recommercegroup

Headquarters : Recommerce Solutions - Cité des Artistes - 54 Avenue Lénine
- 94250 GENTILLY - FRANCE

*The content of this email is confidential and only intended for the
recipient mentioned in the message*. It is strictly forbidden to share this
message in whole or in part with any third party without a written consent
of the sender. If you received this message by mistake, please reply to
this message and follow with its deletion, so that we can ensure such a
mistake does not occur in the future.
*Please note that the Recommerce® brand and logo are registered at the
EUIPO and in Switzerland and belong to Recommerce Solutions in these areas.
Any reproduction, in whole or in part of these trademarks or logos made
without express authorization is prohibited under the European Union's
trademark regulation 2017/1001 and the Swiss Federal law. *

Recommerce® Management System is ISO 14001 (environment), ISO 9001
(quality) and ISO 27001 (Information Security) certified by DNV. The
company's products are certified under the Label "RECQ" verified by DEKRA
Certifications.




Le mar. 11 juil. 2023 à 15:36, Jan Lolling ***@***.***> a
écrit :

> NO, please do not use this mostly out-dated archive!
>
> https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/releases <
> https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/releases>
>
> Best regards
> Jan
>
