### ISSUE TITLE
Failing with an error GoogleAnalyticsBase cannot be resolved

### ISSUE THREAD

**Issue by PipelineAtlas** [jlolling/talendcomp_tGoogleAnalytics4Input#2]
Hi jlolling,

Thanks for this component. I have downloaded this component and provided all jars for it. But still I am getting an error "de.jlo.talendcomp.google.analytics.ga4.GoogleAnalyticsBase cannot be resolved".
Could you please help me with the resolution. 
Also could you please guide on what is dims and matrics in this components.
![16902578531375503696992246215722](https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/assets/140475227/5e508b72-879b-4f8d-9f04-ff28bf774228)

**Comment by jlolling** [comment]
3 questions:
**Where do you have downloaded the component?** 
The only valid source is Github and here the Releases page:
https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/releases

**How do you have installed the components?** 
I recommend this way: 
https://jan-lolling.de/talend/howtos/install_components/how-to-install-talend-custom-components.html

**What version of Java do you running?**
Please check it within your job by adding a tJava and use this command:
System.out.println(System.getProperty("java.version"));

This component expect Java 8 or Java 11 and not higher (just the standard of Talend).

Dimensions and metrics are very well documented on the Google guide pages for GA4. You have to be familiar with it before you start working with this component. 
https://developers.google.com/analytics/devguides/reporting/data/v1

There is also a usage guide for this component linked right in front of this component repository.
https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/blob/master/doc/tGoogleAnalytics4Input.pdf

**Comment by PipelineAtlas** [comment]
Hi jlolling,
Thanks for your quick response.

Please find below answers for your questions.
1. I have downloaded the component from your github release pages itself.
2. I have installed in the same way but I kept the external component under plugin folder. It's working fine.
3. Java version is jre 1.8.202-zulu default. 

Currently the component running without any compilation error but it has run time error as below snapshot.
![20230725_163208](https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/assets/140475227/01e32fd6-2b50-4b51-b1d8-0d3d7a5f400a)
![20230725_163150](https://github.com/jlolling/talendcomp_tGoogleAnalytics4Input/assets/140475227/dde5bb9d-efb1-4548-ad6f-0e1eb591f8bf)

Could you please suggest what would be the error?

**Comment by jlolling** [comment]
You should really learn about GA4. Users is not a valid metric and I guess you have run this false report a couple of times. Now Google does not respond anymore for a while on your wrong report. This is a documented behaviour.

LEARN about what you want to do BEFORE doing it!
